### ISSUE TITLE
Is it supposed to output something?

### ISSUE THREAD

**Issue by kingram6865** [fortrabbit/phpco-docker#1]
This is all I got:

![image](https://user-images.githubusercontent.com/13263318/51155976-5e3b0800-182e-11e9-8248-e43f8f3645bb.png)

**Comment by exstral** [comment]
Yes it normally outputs a progress indicator and a report if it finds anything. The `-p` flags tells it to show progress so at least that should be displayed even if it didn't find any issues.

This is the output when I run it on an old PHP 5.6 project:
<img width="696" alt="screenshot" src="https://user-images.githubusercontent.com/219730/51178899-4b731280-18c4-11e9-92d8-d2b7d965e55b.png">

I have only tried it on a Mac though, so not sure if it works on Windows. Try with some different options? Are you sure you have `.php` files in that `/hera/html/doughnuts` folder?

**Comment by kingram6865** [comment]
I do indeed have files in the directory.
Windows is not a factor, because nothing in your app depends on the OS.
Besides I'm running it in Cygwin.

The strangest things is that it worked before. I ran it initially and received a nice report that
guided my work. I just want to run it again to see if there are any lingering issues.

If there are no issues will it not output any messages?

I ran it on a directory with known problems and still nothing.

**Comment by exstral** [comment]
Correct, if there are no issues it will not output anything. But with the `-p` option it should always output a progress indicator like the screenshot above. 29ms is also way too fast for any actual code analysis, most likely it can't find any files to analyse.

Maybe something with the volume mounts in the `phpco` command? Try running the full docker command directly:
```bash
docker run --init -v $PWD:/mnt/src:cached --rm -u "$(id -u):$(id -g)" frbit/phpco:latest -p --colors --extensions=php --runtime-set testVersion 7.2 .
```

**Comment by kingram6865** [comment]
Yeah that didn't produce anything either.
This is really strange because it has worked before, and nothing has changed in my system since Dec 31 when I last ran it.

Running 'tree' in my directory shows that there are clearly files there to process.

366 directories, 2157 file

What other ways are there to debug what's happening here?

**Comment by Kolin** [comment]
I've had the same problem trying to run this via WLS.

The problem here is that $PWD in WLS will be something like `/mnt/d/site/src` whereas docker for windows needs the windows path.

I've been running this as a workaround: 

```
phpco() { docker run --init -v "D:\site\src":/mnt/src:cached --rm -u "$(id -u):$(id -g)" frbit/phpco:latest $@; return $?; }
phpco -p --colors --extensions=php --runtime-set testVersion 7.2 .
```

**Comment by kingram6865** [comment]
What is WLS?

I am running in a cygwin environment. I get an error when attempting to try it your way Kolin.

```
$ docker run --init -v "C:\site\src":/mnt/src:cached frbit/phpco:latest -p --colors --extensions=php --runtime-set testVersion 7.2
C:\Applications\Virtual Machines\Docker Toolbox\docker.exe: Error response from daemon: invalid volume specification: 'C:\site\src:/mnt/src:cached'.
See 'C:\Applications\Virtual Machines\Docker Toolbox\docker.exe run --help'.

```

**Comment by Kolin** [comment]
https://docs.microsoft.com/en-us/windows/wsl/about

I'm also using docker for windows rather than docker toolbox. I'm not sure what the correct paths for docker toolbox will be.

**Comment by kingram6865** [comment]
Ah, I see.
I'm still running Windows 7. Didn't trust Windows 10 when I built this machine.

So, I'm still stuck I guess.

**Comment by kingram6865** [comment]
Found a solution to get past the directory issue:

```
$ docker run --init -v "/cygdrive/c/site/src":/mnt/src:cached frbit/phpco:latest -p --colors --extensions=php --runtime-set testVersion 7.2 .

Time: 30ms; Memory: 6Mb
```
Still no process output

**Comment by exstral** [comment]
Hi, happy to see you helping each other out! I know less about windows, but I do know that the `:cached` extra setting on the docker volume is specific to Docker Desktop for Mac. 
https://docs.docker.com/docker-for-mac/osxfs-caching/

Hopefully the Windows version should ignore it, but you could try the command without it?

**Comment by erinbit** [comment]
Closing this for now for lack of feedback. Feel free to reopen if you have more ideas.
