### ISSUE TITLE
Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator

### ISSUE THREAD

**Issue by lakano** [fortrabbit/phpco-docker#3]
Hello,
I'm trying to use it but I have this error, do you have any idea of how to fix it please?
I'm under GNU/Linux Fedora 30.
I doesn't have recursive folders, I've also tested with an empty vendor/ folder.
I've tried to use the direct docker command too.
I've also tried the previous version 8.2.0

Regards,

```
% phpco() { docker run --init -v $PWD:/mnt/src:cached --rm -u "$(id -u):$(id -g)" frbit/phpco:latest $@; return $?; }

% phpco -p --colors --extensions=php --runtime-set testVersion 7.2 .

Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(/mnt/src): failed to open dir: Permission denied in /usr/local/lib/php/PHP/CodeSniffer/src/Files/FileList.php:82
Stack trace:
#0 /usr/local/lib/php/PHP/CodeSniffer/src/Files/FileList.php(82): RecursiveDirectoryIterator->__construct('/mnt/src', 4608)
#1 /usr/local/lib/php/PHP/CodeSniffer/src/Runner.php(382): PHP_CodeSniffer\Files\FileList->__construct(Object(PHP_CodeSniffer\Config), Object(PHP_CodeSniffer\Ruleset))
#2 /usr/local/lib/php/PHP/CodeSniffer/src/Runner.php(114): PHP_CodeSniffer\Runner->run()
#3 /usr/local/bin/phpcs(18): PHP_CodeSniffer\Runner->runPHPCS()
#4 {main}
  thrown in /usr/local/lib/php/PHP/CodeSniffer/src/Files/FileList.php on line 82

```

**Comment by exstral** [comment]
Thank you for the detailed report. Looks like Docker is not allowed to read from the current directory. 

What is the permissions in the directory where you run this command, and what is the output of
`echo "$(id -u):$(id -g)"`

**Comment by lakano** [comment]
Thanks for the quick answer!
```
% echo "$(id -u):$(id -g)"
1000:1000
% ls . -lahd
drwxrwxr-x. 19 guillaume guillaume 4,0K  2 juil. 19:39 .
% id guillaume
uid=1000(guillaume) gid=1000(guillaume) groupes=1000(guillaume),10(wheel),975(docker)

```

**Comment by lakano** [comment]
I've also tried with sudo, to be sure

**Comment by lakano** [comment]
Hello @exstral,
do you have any suggestions or tests I could run to help please? :)

**Comment by erinbit** [comment]
Hi, sorry for the enormous delay here. Closing for now, hope you might have found a solution. Feel free to reopen if you need more help. We will be more active on GitHub in the future.
