### ISSUE TITLE
Run out of memory 

### ISSUE THREAD

**Issue by blanxii** [fortrabbit/phpco-docker#5]
When running this instance on a huge project I'm getting a out of memory issue. Gonna provide PR for this.

`Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 16777224 bytes) in /usr/local/lib/php/PHP/CodeSniffer/src/Tokenizers/PHP.php on line 1449`

**Comment by blanxii** [comment]
Edited, first was trying to setup a env variable but saw was already set up, just updating the readme if anyone hits the same problem they can just edit it :)

**Comment by blanxii** [comment]
*Second edit* maybe if I think different.. why you want other value that is not -1 (use all?) maybe for me it make more sense if I'm trying to profile the upgrade of application I don't care using 10GB of RAM, isn't it? What do you think guys? should I go for the -1 by default?

**Comment by erinbit** [comment]
Sorry for the delayed response. Thank you for taking time to report back on your findings :)

I would say that `-1` sounds like a good idea. I will add it.

**Comment by blanxii** [comment]
@esbiorn you have it here https://github.com/fortrabbit/phpco-docker/pull/6/files :)

**Comment by erinbit** [comment]
Ah sorry didn't see the pull request. Added it in a new commit. Thanks!
