### ISSUE TITLE
The output suggests to use phpcbf, which is not available

### ISSUE THREAD

**Issue by afilina** [fortrabbit/phpco-docker#9]
Feature request: add phpcbf into the image, so that one could automatically fix whatever the output is suggesting. Otherwise, we need to figure out the full installation, bringing us back to square one.

**Comment by erinbit** [comment]
Thank you for your feature request. Unfortunately we are no longer maintaining this. Feel free to fork and run it yourself :)

**Comment by erinbit** [comment]
Thank you for your feature request. Unfortunately we are no longer maintaining this. Feel free to fork and run it yourself :)
